//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simpress.SisAmigos.UI.Windows
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ESCOLARIDADE
    {
        public int ID_ESCOLARIDADE { get; set; }
        public string DS_ESCOLARIDADE { get; set; }
    }
}
